"""
routers/literature.py

POST /api/search_literature   — legacy simple search (kept for compatibility)
POST /api/search_stream       — SSE streaming search with AI query expansion
POST /api/generate_summary    — AI-powered critical summary (falls back to heuristic)
"""

import json
import logging
import os

from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse

from models import (
    CitationPoint,
    CrossReferenceRequest,
    CriticalSummary,
    Paper,
    PaperSummary,
    SearchRequest,
    SearchResponse,
    StreamSearchRequest,
    SummarizePaperRequest,
    SummaryRequest,
)
from routers.settings import load_settings, load_settings_for_user
from services.auth import get_current_user
from services.ai_provider import AIProvider
from services.literature_engine import LiteratureEngine
from services.paper_fetcher import FetchSettings
from services.paper_summarizer import summarize_paper
from services.provider_resolver import build_provider_for_user_config
from services.query_expander import (
    expand_query,
    generate_tentative_title,
    heuristic_expand_query,
    heuristic_tentative_title,
)
from services.project_repo import (
    load_project as load_session,
    replace_project_papers,
    save_literature_search_state,
)
from services.token_context import TokenContext

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api", tags=["literature"])

_engine = LiteratureEngine(ncbi_api_key=os.getenv("NCBI_API_KEY"))
_SEARCH_SOURCES = [
    "pubmed",
    "pmc",
    "openalex",
    "semantic_scholar",
    "crossref",
    "europe_pmc",
    "clinical_trials",
    "arxiv",
]

# ── Helpers ───────────────────────────────────────────────────────────────────

def _sse(data: dict) -> str:
    return f"data: {json.dumps(data)}\n\n"


def _get_provider() -> AIProvider | None:
    cfg = load_settings()
    # Local providers (Ollama, llama.cpp) don't need an API key
    if cfg.api_key or cfg.provider in ("ollama", "llamacpp"):
        return AIProvider(cfg)
    return None


async def _get_provider_for_user(user_id: str) -> AIProvider | None:
    cfg = await load_settings_for_user(user_id)
    provider = await build_provider_for_user_config(user_id, cfg)
    if provider:
        return provider
    logger.warning(
        "No usable AI provider for user %s (provider=%r, has_api_key=%s). "
        "User may not have saved settings or key decryption failed.",
        user_id, cfg.provider, cfg.has_api_key,
    )
    return None


# ── Legacy simple search ───────────────────────────────────────────────────────

@router.post("/search_literature", response_model=SearchResponse)
async def search_literature(payload: SearchRequest) -> SearchResponse:
    papers = await _engine.search_all(payload.query, payload.max_results_per_source)
    return SearchResponse(
        papers=papers,
        total=len(papers),
        sources_queried=["pubmed", "pmc", "openalex", "semantic_scholar", "crossref", "europe_pmc", "clinical_trials", "arxiv"],
    )


# ── SSE streaming search ───────────────────────────────────────────────────────

@router.post("/search_stream")
async def search_stream(payload: StreamSearchRequest, user=Depends(get_current_user)) -> StreamingResponse:
    """
    Server-Sent Events endpoint.  Each event is a JSON object on a `data:` line.

    Event sequence:
      ai_queries      → expanded search strings generated by LLM
      papers          → batch of papers from one source
      source_error    → a source failed (non-fatal)
      source_done     → a source finished
      deduplicating   → cross-source dedup in progress
      enriching       → Unpaywall OA enrichment in progress
      complete        → final enriched + sorted paper list
      error           → fatal error (whole pipeline failed)
    """

    async def generate():
        search_state: dict = {
            "status": "streaming",
            "query": payload.query,
            "total_limit": payload.total_limit,
            "warnings": [],
            "source_progress": {},
            "sources_done": [],
            "sources_error": {},
            "is_deduplicating": False,
            "ranking_info": None,
            "is_enriching": False,
            "expanded_queries": [],
            "pubmed_queries": [],
            "mesh_terms": [],
            "boolean_query": "",
            "pico": {},
            "framework_elements": {},
            "framework_used": "",
            "question_type": None,
            "secondary_frameworks_considered": [],
            "study_type_filters": [],
            "ai_rationale": "",
            "facets": {},
            "strategy_notes": [],
            "tentative_title": "",
            "source_papers": {},
            "current_papers": [],
        }

        async def _persist() -> None:
            if payload.project_id:
                await save_literature_search_state(payload.project_id, search_state, query=payload.query)

        try:
            if payload.project_id:
                project = await load_session(user["id"], payload.project_id)
                if project is None:
                    yield _sse({"type": "error", "message": "Project not found."})
                    return

            # 1. AI query expansion ────────────────────────────────────────────
            queries = [payload.query]
            pubmed_queries: list[str] = []
            await _persist()
            if payload.use_ai_expansion:
                provider = await _get_provider_for_user(user["id"])
                if provider:
                    try:
                        async with TokenContext(project_id=payload.project_id, user_id=user["id"], stage="query_expansion"):
                            generated_title = await generate_tentative_title(
                                provider,
                                payload.query,
                                article_type=payload.article_type or "",
                            )
                            expanded = await expand_query(provider, payload.query, article_type=payload.article_type or "")
                        queries = expanded.queries
                        pubmed_queries = expanded.pubmed_queries
                        search_state.update({
                            "expanded_queries": expanded.queries,
                            "pubmed_queries": expanded.pubmed_queries,
                            "mesh_terms": expanded.mesh_terms,
                            "boolean_query": expanded.boolean_query,
                            "pico": expanded.pico or expanded.framework_elements,
                            "framework_elements": expanded.framework_elements,
                            "framework_used": expanded.framework_used,
                            "framework_justification": expanded.framework_justification,
                            "question_type": expanded.question_type,
                            "secondary_frameworks_considered": expanded.secondary_frameworks_considered,
                            "study_type_filters": expanded.study_type_filters,
                            "ai_rationale": expanded.rationale,
                            "facets": expanded.facets,
                            "strategy_notes": expanded.strategy_notes,
                            "tentative_title": generated_title or expanded.tentative_title or "",
                        })
                        await _persist()
                        yield _sse({
                            "type": "ai_queries",
                            "data": {
                                "queries":                  expanded.queries,
                                "pubmed_queries":           expanded.pubmed_queries,
                                "mesh_terms":               expanded.mesh_terms,
                                "boolean_query":            expanded.boolean_query,
                                "pico":                     expanded.pico or expanded.framework_elements,
                                "framework_elements":       expanded.framework_elements,
                                "study_type_filters":       expanded.study_type_filters,
                                "rationale":                expanded.rationale,
                                "facets":                   expanded.facets,
                                "strategy_notes":           expanded.strategy_notes,
                                "framework_used":           expanded.framework_used,
                                "framework_justification":  expanded.framework_justification,
                                "question_type":            expanded.question_type,
                                "secondary_frameworks_considered": expanded.secondary_frameworks_considered,
                                "tentative_title":          generated_title or expanded.tentative_title,
                            },
                        })
                    except Exception as exc:
                        logger.warning("Query expansion failed: %s", exc)
                        fallback = heuristic_expand_query(payload.query, article_type=payload.article_type or "")
                        queries = fallback.queries
                        pubmed_queries = fallback.pubmed_queries
                        search_state.update({
                            "expanded_queries": fallback.queries,
                            "pubmed_queries": fallback.pubmed_queries,
                            "mesh_terms": fallback.mesh_terms,
                            "boolean_query": fallback.boolean_query,
                            "pico": fallback.pico or fallback.framework_elements,
                            "framework_elements": fallback.framework_elements,
                            "framework_used": fallback.framework_used,
                            "framework_justification": fallback.framework_justification,
                            "question_type": fallback.question_type,
                            "secondary_frameworks_considered": fallback.secondary_frameworks_considered,
                            "study_type_filters": fallback.study_type_filters,
                            "ai_rationale": fallback.rationale,
                            "facets": fallback.facets,
                            "strategy_notes": fallback.strategy_notes,
                            "tentative_title": fallback.tentative_title or "",
                        })
                        search_state["warnings"].append(
                            f"AI expansion unavailable: {exc}. Using heuristic keyword search strategy."
                        )
                        await _persist()
                        yield _sse({"type": "warning", "message": f"AI expansion unavailable: {exc}. Using heuristic keyword search strategy."})
                else:
                    fallback = heuristic_expand_query(payload.query, article_type=payload.article_type or "")
                    queries = fallback.queries
                    pubmed_queries = fallback.pubmed_queries
                    search_state.update({
                        "expanded_queries": fallback.queries,
                        "pubmed_queries": fallback.pubmed_queries,
                        "mesh_terms": fallback.mesh_terms,
                        "boolean_query": fallback.boolean_query,
                        "pico": fallback.pico or fallback.framework_elements,
                        "framework_elements": fallback.framework_elements,
                        "framework_used": fallback.framework_used,
                        "framework_justification": fallback.framework_justification,
                        "question_type": fallback.question_type,
                        "secondary_frameworks_considered": fallback.secondary_frameworks_considered,
                        "study_type_filters": fallback.study_type_filters,
                        "ai_rationale": fallback.rationale,
                        "facets": fallback.facets,
                        "strategy_notes": fallback.strategy_notes,
                        "tentative_title": fallback.tentative_title or heuristic_tentative_title(payload.query, article_type=payload.article_type or ""),
                    })
                    search_state["warnings"].append(
                        "No AI provider configured. Using heuristic keyword search strategy instead of raw query."
                    )
                    await _persist()
                    yield _sse({"type": "warning", "message": "No AI provider configured. Using heuristic keyword search strategy instead of raw query."})

            # 2. Concurrent paginated search (streams events as sources finish) ─
            async for event in _engine.search_all_streaming(
                queries, payload.total_limit,
                pubmed_queries=pubmed_queries or None,
            ):
                event_type = event.get("type")
                source = event.get("source")
                if event_type == "papers" and source:
                    batch = event.get("papers") or []
                    search_state["source_progress"][source] = event.get("count", len(batch))
                    search_state["source_papers"][source] = batch
                    current = list(search_state.get("current_papers") or [])
                    current.extend(batch)
                    search_state["current_papers"] = current
                    await _persist()
                elif event_type == "source_done" and source:
                    done = set(search_state.get("sources_done") or [])
                    done.add(source)
                    search_state["sources_done"] = sorted(done)
                    await _persist()
                elif event_type == "source_error" and source:
                    errors = dict(search_state.get("sources_error") or {})
                    errors[source] = event.get("message") or "Unknown source failure"
                    search_state["sources_error"] = errors
                    done = set(search_state.get("sources_done") or [])
                    done.add(source)
                    search_state["sources_done"] = sorted(done)
                    await _persist()
                elif event_type == "deduplicating":
                    search_state["is_deduplicating"] = True
                    await _persist()
                elif event_type == "ranking":
                    search_state["ranking_info"] = {
                        "candidates": event.get("candidates", 0),
                        "selected": event.get("selected", 0),
                        "requested": event.get("requested", payload.total_limit),
                    }
                    await _persist()
                elif event_type == "enriching":
                    search_state["is_enriching"] = True
                    await _persist()
                elif event_type == "complete":
                    final_papers = event.get("papers") or []
                    search_state["status"] = "done"
                    search_state["is_enriching"] = False
                    search_state["sources_done"] = list(_SEARCH_SOURCES)
                    search_state["current_papers"] = final_papers
                    await _persist()
                    if payload.project_id:
                        await replace_project_papers(payload.project_id, final_papers)
                elif event_type == "warning" and event.get("message"):
                    warnings = list(search_state.get("warnings") or [])
                    warnings.append(event["message"])
                    search_state["warnings"] = warnings
                    await _persist()
                yield _sse(event)

        except Exception as exc:
            logger.exception("search_stream fatal error")
            search_state["status"] = "error"
            search_state["error"] = str(exc)
            await _persist()
            yield _sse({"type": "error", "message": str(exc)})

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


# ── Per-paper detailed summary ─────────────────────────────────────────────────

async def _fetch_settings_for_user(user_id: str, project_folder: str | None = None) -> FetchSettings:
    """Load user's PDF/Sci-Hub preferences and build a FetchSettings instance."""
    cfg = await load_settings_for_user(user_id)
    return FetchSettings(
        pdf_save_enabled=cfg.pdf_save_enabled or bool(project_folder),
        pdf_save_path=cfg.pdf_save_path,
        project_folder=project_folder,
        sci_hub_enabled=cfg.sci_hub_enabled,
        http_proxy=cfg.http_proxy,
    )


@router.post("/summarize_paper", response_model=PaperSummary)
async def summarize_paper_endpoint(payload: SummarizePaperRequest, user=Depends(get_current_user)) -> PaperSummary:
    """
    Generate a detailed reviewer-grade analysis for a single paper.
    Fetches full text (PMC XML > OA PDF > Sci-Hub > abstract) then runs the LLM template.
    """
    provider = await _get_provider_for_user(user["id"])
    if not provider:
        raise HTTPException(status_code=400, detail="No AI provider configured. Open Settings to add one.")
    project_id = payload.project_id or payload.session_id
    project_folder: str | None = None
    if project_id:
        project = await load_session(user["id"], project_id)
        if project is not None:
            project_folder = project.get("project_folder")
    fs = await _fetch_settings_for_user(user["id"], project_folder)
    async with TokenContext(project_id=project_id, user_id=user["id"], stage="summarize_paper"):
        return await summarize_paper(
            provider, payload.paper, payload.query,
            fetch_settings=fs, session_id=project_id,
        )


# ── Critical summary ───────────────────────────────────────────────────────────

@router.post("/generate_summary", response_model=CriticalSummary)
async def generate_summary(payload: SummaryRequest, user=Depends(get_current_user)) -> CriticalSummary:
    """
    Tries AI summary first (OpenAI); falls back to heuristic extraction.
    """
    provider = await _get_provider_for_user(user["id"])
    if provider and payload.papers:
        try:
            return await _ai_summary(provider, payload.papers, payload.key_idea or "")
        except Exception as exc:
            logger.warning("AI summary failed (%s), falling back to heuristic.", exc)
    return _heuristic_summary(payload.papers, payload.key_idea or "")


# ── AI summary (OpenAI) ────────────────────────────────────────────────────────

_SUMMARY_SYSTEM = """\
You are a senior academic researcher conducting a systematic literature review.
Analyse the provided research papers and return a structured critical summary as JSON.

Return ONLY valid JSON in this exact shape — no markdown, no extra text:
{
  "core_points": [
    "Specific, evidence-backed statement drawn from the literature (4-6 items)"
  ],
  "new_data_explained": [
    "Concrete empirical finding, statistic, or novel result cited in the abstracts (4-6 items)"
  ],
  "cross_references": [
    {
      "paper_title": "Exact paper title",
      "doi": "DOI string or null",
      "relevance": "1-2 sentences explaining why this paper is central to the research question"
    }
  ]
}

Rules:
- Be specific — cite actual numbers, effect sizes, p-values, or percentages where mentioned.
- Do NOT fabricate data not present in the abstracts.
- Cross-reference all papers provided.
"""


async def _ai_summary(provider: AIProvider, papers: list[Paper], key_idea: str) -> CriticalSummary:
    blocks = []
    for i, p in enumerate(papers[:25], 1):  # cap at 25 to stay within context limits
        block = f"[{i}] {p.title} ({p.year or 'n.d.'})\n"
        block += f"Authors: {', '.join(p.authors[:3])}\n"
        if p.journal:
            block += f"Journal: {p.journal}\n"
        if p.citation_count is not None:
            block += f"Citations: {p.citation_count:,}\n"
        if p.abstract:
            block += f"Abstract: {p.abstract[:900]}\n"
        blocks.append(block)

    user_msg = (
        f"Research question: {key_idea}\n\n"
        f"Papers ({len(blocks)} of {len(papers)}):\n\n"
        + "\n---\n".join(blocks)
    )

    raw = await provider.complete(
        system=_SUMMARY_SYSTEM,
        user=user_msg,
        json_mode=True,
        temperature=0.2,
    )
    data = json.loads(raw)
    return CriticalSummary(
        core_points=data.get("core_points") or [],
        new_data_explained=data.get("new_data_explained") or [],
        cross_references=[
            CitationPoint(**ref)
            for ref in (data.get("cross_references") or [])
            if isinstance(ref, dict)
        ],
    )


# ── Cross-reference pipeline ───────────────────────────────────────────────────

@router.post("/sessions/{session_id}/stream_cross_references")
async def stream_cross_references_endpoint(
    session_id: str,
    payload: CrossReferenceRequest,
    user=Depends(get_current_user),
) -> StreamingResponse:
    """
    SSE endpoint that fetches and summarizes papers cited by the session's primary papers.

    Depth 1: papers cited by primary (depth=0) papers
    Depth 2: additionally papers cited by those depth-1 papers

    Event types: start, resolving, paper_done, skip, depth_complete, complete, warning, error
    """
    provider = await _get_provider_for_user(user["id"])
    if not provider:
        raise HTTPException(status_code=400, detail="No AI provider configured. Open Settings to add one.")

    fs = await _fetch_settings_for_user(user["id"])
    session = await load_session(user["id"], session_id)
    if session is None:
        raise HTTPException(status_code=404, detail="Session not found.")
    session_query = str(session.get("query") or "")

    async def generate():
        try:
            from services.cross_reference_engine import stream_cross_references
            async with TokenContext(project_id=session_id, user_id=user["id"], stage="cross_reference"):
                async for event in stream_cross_references(
                    session_id=session_id,
                    depth=payload.depth,
                    provider=provider,
                    query=session_query,
                    fetch_settings=fs,
                    purpose_filter=payload.purpose_filter or [],
                ):
                    yield _sse(event)
        except Exception as exc:
            logger.exception("stream_cross_references fatal error")
            yield _sse({"type": "error", "message": str(exc)})

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


@router.get("/sessions/{session_id}/cross_reference_stats")
async def cross_reference_stats(
    session_id: str,
    user=Depends(get_current_user),
) -> dict:
    """Return paper counts by depth (0=primary, 1=depth-1, 2=depth-2)."""
    from services.cross_reference_engine import get_cross_reference_stats
    return await get_cross_reference_stats(session_id)


# ── /projects/ aliases for cross-reference endpoints ─────────────────────────

@router.post("/projects/{project_id}/stream_cross_references")
async def stream_cross_references_projects(
    project_id: str,
    payload: CrossReferenceRequest,
    user=Depends(get_current_user),
) -> StreamingResponse:
    return await stream_cross_references_endpoint(project_id, payload, user)


@router.get("/projects/{project_id}/cross_reference_stats")
async def cross_reference_stats_projects(
    project_id: str,
    user=Depends(get_current_user),
) -> dict:
    from services.cross_reference_engine import get_cross_reference_stats
    return await get_cross_reference_stats(project_id)


# ── Heuristic fallback summary ─────────────────────────────────────────────────

def _heuristic_summary(papers: list[Paper], key_idea: str) -> CriticalSummary:
    EMPIRICAL = {
        "found", "showed", "demonstrated", "reported", "identified",
        "revealed", "observed", "indicated", "confirmed", "established",
        "suggests", "suggested",
    }
    core: list[str] = []
    new_data: list[str] = []
    refs: list[CitationPoint] = []

    for p in papers:
        abstract = (p.abstract or "").strip().replace("\n", " ")
        if abstract:
            sentences = [s.strip() for s in abstract.split(". ") if len(s.strip()) > 20]
            if sentences:
                core.append(sentences[0])
            for s in sentences[1:]:
                if any(kw in s.lower().split() for kw in EMPIRICAL):
                    new_data.append(s)
                    break
        cite = (
            f"Cited by {p.citation_count:,} works."
            if p.citation_count is not None
            else "Citation count unavailable."
        )
        refs.append(CitationPoint(
            paper_title=p.title,
            doi=p.doi,
            relevance=f"[{p.source.upper()}] {p.year or 'n.d.'} · {cite}",
        ))

    return CriticalSummary(
        core_points=list(dict.fromkeys(core))[:6],
        new_data_explained=list(dict.fromkeys(new_data))[:6],
        cross_references=refs,
    )
