"""
search_guidelines.py

Loads pre-distilled systematic-review search methodology guidelines from
data/search_guidelines.json and returns them as formatted text for injection
into the query_expander.py system prompt.

Generated by scripts/extract_search_guidelines.py — if the file doesn't
exist yet, all functions return empty strings and the app works normally.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

_GUIDELINES_PATH = Path(__file__).parent.parent / "data" / "search_guidelines.json"

# Keys to always include in the query-expander injection
_CORE_KEYS = [
    "general",
    "pico",
    "framework_selection",
    "boolean_strategy",
    "mesh_and_vocabulary",
    "synonym_collection",
    "advanced_techniques",
    "database_selection",
    "study_filters",
    "grey_literature",
]

# Keys for study selection / quality (used in summarizer/reviewer injection)
_QUALITY_KEYS = [
    "study_selection",
    "risk_of_bias",
    "search_reporting",
]


@lru_cache(maxsize=1)
def _load() -> dict[str, list[str]]:
    if not _GUIDELINES_PATH.exists():
        logger.info(
            "search_guidelines.json not found at %s — "
            "run scripts/extract_search_guidelines.py to generate it",
            _GUIDELINES_PATH,
        )
        return {}
    try:
        data = json.loads(_GUIDELINES_PATH.read_text(encoding="utf-8"))
        total = sum(len(v) for v in data.values() if isinstance(v, list))
        logger.info("Loaded %d search methodology guidelines", total)
        return data
    except Exception as exc:
        logger.warning("Failed to load search_guidelines.json: %s", exc)
        return {}


def get_search_strategy_guidelines() -> str:
    """
    Return formatted search-strategy guidelines to inject into the
    query_expander system prompt.

    Covers: PICO, boolean logic, MeSH, database selection, study filters,
    grey literature, and general principles.
    Returns empty string if file not yet generated.
    """
    data = _load()
    if not data:
        return ""

    lines: list[str] = [
        "## Systematic Review Search Standards",
        "(from Cochrane Handbook, MECIR standards, and Doing a Systematic Review)",
    ]

    for key in _CORE_KEYS:
        items = data.get(key, [])
        if not items:
            continue
        label = key.replace("_", " ").title()
        lines.append(f"\n### {label}")
        for item in items:
            lines.append(f"- {item}")

    return "\n".join(lines)


def get_quality_assessment_guidelines() -> str:
    """
    Return study-selection, risk-of-bias, and PRISMA reporting guidelines.
    Used for injecting into the paper summarizer and peer reviewer prompts.
    """
    data = _load()
    if not data:
        return ""

    lines: list[str] = ["## Study Quality & Reporting Standards (Cochrane/MECIR)"]

    for key in _QUALITY_KEYS:
        items = data.get(key, [])
        if not items:
            continue
        label = key.replace("_", " ").title()
        lines.append(f"\n### {label}")
        for item in items:
            lines.append(f"- {item}")

    return "\n".join(lines)


def guidelines_available() -> bool:
    return bool(_load())
